import { cacheYoutubeSubtitleCues, type YoutubeSubtitleCue } from './subtitle-overlay';
import { logDebug } from '../../shared/debug';

type YoutubePlayerResponse = {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: Array<{
        baseUrl?: string;
        languageCode?: string;
        kind?: string;
        name?: unknown;
      }>;
    };
  };
};

const RENDERED_CAPTION_WAIT_MS = 3000;
const FULL_TRACK_INITIAL_LOOKAHEAD_MS = 12_000;
const FULL_TRACK_INITIAL_MAX_CUES = 6;
const FULL_TRACK_INITIAL_CUE_GRACE_MS = 500;

export async function collectYoutubeSubtitleSegments(
  preferredLanguage = 'auto',
  options: {
    enableAutoGeneratedCaptions?: boolean;
  } = {},
): Promise<Array<{ id: string; text: string }>> {
  const enableAutoGeneratedCaptions = options.enableAutoGeneratedCaptions ?? true;
  logDebug('youtube subtitle capture started', {
    preferredLanguage,
    enableAutoGeneratedCaptions,
  });
  const immediateRenderedCue = collectImmediateRenderedYoutubeCaptionCue();
  if (immediateRenderedCue) {
    logDebug('youtube subtitle captured', { originalText: immediateRenderedCue.text });
    cacheYoutubeSubtitleCues([immediateRenderedCue]);
    return [{ id: immediateRenderedCue.id, text: immediateRenderedCue.text }];
  }

  const trackUrls = await findCaptionTrackUrls(preferredLanguage);
  if (trackUrls.length === 0) {
    logDebug('youtube subtitle track not found');
    cacheYoutubeSubtitleCues([]);
    return [];
  }

  let lastFailureStatus: number | undefined;
  for (const [index, trackUrl] of trackUrls.entries()) {
    const response = await fetch(trackUrl);
    if (!response.ok) {
      lastFailureStatus = response.status;
      logDebug('youtube subtitle track request failed', {
        attempt: index + 1,
        status: response.status,
      });
      continue;
    }

    const cues = parseTimedText(await response.text());
    if (cues.length === 0) {
      continue;
    }

    cacheYoutubeSubtitleCues(cues);
    const initialSegments = selectInitialTrackCues(cues).map(({ id, text }) => ({ id, text }));
    initialSegments.forEach((segment) => {
      logDebug('youtube subtitle captured', { originalText: segment.text });
    });
    return initialSegments;
  }

  if (lastFailureStatus !== undefined) {
    throw new Error(`字幕轨道读取失败：${lastFailureStatus}`);
  }

  const renderedCues = await collectRenderedYoutubeCaptionCues({
    enableAutoGeneratedCaptions,
  });
  if (renderedCues.length > 0) {
    renderedCues.forEach((cue) => {
      logDebug('youtube subtitle captured', { originalText: cue.text });
    });
    cacheYoutubeSubtitleCues(renderedCues);
    return renderedCues.map(({ id, text }) => ({ id, text }));
  }

  throw new Error('字幕轨道存在，但 YouTube 返回了空字幕内容。已尝试多个字幕格式和轨道，请确认视频字幕可在播放器中打开。');
}

async function findCaptionTrackUrls(preferredLanguage: string): Promise<string[]> {
  const playerResponse = readPlayerResponseFromWindow() ?? readPlayerResponseFromScripts();
  const trackUrls = selectCaptionTrackUrls(playerResponse, preferredLanguage, 'page-state');
  if (trackUrls.length > 0) {
    return trackUrls;
  }

  const fallbackPlayerResponse = await readPlayerResponseFromCurrentWatchPage();
  return selectCaptionTrackUrls(fallbackPlayerResponse, preferredLanguage, 'watch-html');
}

function selectCaptionTrackUrls(
  playerResponse: YoutubePlayerResponse | null,
  preferredLanguage: string,
  source: 'page-state' | 'watch-html',
): string[] {
  const tracks =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const tracksWithUrls = tracks.filter((track) => track.baseUrl);
  const normalizedPreferredLanguage = normalizeLanguageCode(preferredLanguage);
  const preferredTracks =
    normalizedPreferredLanguage === 'auto'
      ? [
          ...tracksWithUrls.filter(
          (track) => normalizeLanguageCode(track.languageCode ?? '') === 'en' && track.kind !== 'asr',
          ),
          ...tracksWithUrls.filter(
            (track) => normalizeLanguageCode(track.languageCode ?? '') !== 'en' && track.kind !== 'asr',
          ),
          ...tracksWithUrls.filter((track) => track.kind === 'asr'),
        ]
      : [
          ...tracksWithUrls.filter(
          (track) => normalizeLanguageCode(track.languageCode ?? '') === normalizedPreferredLanguage,
          ),
          ...tracksWithUrls.filter(
            (track) => normalizeLanguageCode(track.languageCode ?? '') !== normalizedPreferredLanguage && track.kind !== 'asr',
          ),
          ...tracksWithUrls.filter(
            (track) => normalizeLanguageCode(track.languageCode ?? '') !== normalizedPreferredLanguage && track.kind === 'asr',
          ),
        ];

  return uniqueStrings(
    preferredTracks.flatMap((track) => createCaptionTrackUrlVariants(track.baseUrl ?? '')),
  );
}

function createCaptionTrackUrlVariants(baseUrl: string): string[] {
  if (!baseUrl) {
    return [];
  }

  return uniqueStrings([
    baseUrl,
    withCaptionFormat(baseUrl, 'json3'),
    withCaptionFormat(baseUrl, 'vtt'),
  ]);
}

function withCaptionFormat(url: string, format: 'json3' | 'vtt'): string {
  try {
    const parsedUrl = new URL(url);
    parsedUrl.searchParams.set('fmt', format);
    return parsedUrl.toString();
  } catch {
    const separator = url.includes('?') ? '&' : '?';
    return `${url}${separator}fmt=${format}`;
  }
}

function uniqueStrings(values: string[]): string[] {
  return Array.from(new Set(values.filter(Boolean)));
}

async function readPlayerResponseFromCurrentWatchPage(): Promise<YoutubePlayerResponse | null> {
  try {
    const response = await fetch(window.location.href);
    if (!response.ok) {
      logDebug('youtube watch html fallback request failed', { status: response.status });
      return null;
    }

    const html = await response.text();
    return readPlayerResponseFromText(html);
  } catch (error) {
    logDebug('youtube watch html fallback threw', {
      message: error instanceof Error ? error.message : String(error),
    });
    return null;
  }
}

function normalizeLanguageCode(languageCode: string): string {
  return languageCode.trim().toLowerCase().split('-')[0] || 'auto';
}

function readPlayerResponseFromWindow(): YoutubePlayerResponse | null {
  const candidate = (window as unknown as { ytInitialPlayerResponse?: YoutubePlayerResponse })
    .ytInitialPlayerResponse;
  return candidate ?? null;
}

function readPlayerResponseFromScripts(): YoutubePlayerResponse | null {
  for (const script of Array.from(document.scripts)) {
    const playerResponse = readPlayerResponseFromText(script.textContent ?? '');
    if (playerResponse) {
      return playerResponse;
    }
  }

  return null;
}

function readPlayerResponseFromText(text: string): YoutubePlayerResponse | null {
  const marker = 'ytInitialPlayerResponse';
  const markerIndex = text.indexOf(marker);
  if (markerIndex === -1) {
    return null;
  }

  const jsonStart = text.indexOf('{', markerIndex);
  if (jsonStart === -1) {
    return null;
  }

  const jsonText = readBalancedJsonObject(text, jsonStart);
  if (!jsonText) {
    return null;
  }

  try {
    return JSON.parse(jsonText) as YoutubePlayerResponse;
  } catch {
    return null;
  }
}

function readBalancedJsonObject(text: string, startIndex: number): string {
  let depth = 0;
  let inString = false;
  let escaping = false;

  for (let index = startIndex; index < text.length; index += 1) {
    const char = text[index];

    if (escaping) {
      escaping = false;
      continue;
    }

    if (char === '\\') {
      escaping = true;
      continue;
    }

    if (char === '"') {
      inString = !inString;
      continue;
    }

    if (inString) {
      continue;
    }

    if (char === '{') {
      depth += 1;
    } else if (char === '}') {
      depth -= 1;
      if (depth === 0) {
        return text.slice(startIndex, index + 1);
      }
    }
  }

  return '';
}

function parseTimedText(xml: string): YoutubeSubtitleCue[] {
  const trimmed = xml.trim();
  if (!trimmed) {
    return [];
  }

  if (trimmed.startsWith('{')) {
    return parseJson3TimedText(trimmed);
  }

  if (trimmed.startsWith('WEBVTT')) {
    return parseWebVttTimedText(trimmed);
  }

  const xmlDocument = new DOMParser().parseFromString(trimmed, 'text/xml');
  const transcriptTextCues = Array.from(xmlDocument.querySelectorAll('text'))
    .map((node, index) => {
      const text = normalizeCueText(node.textContent ?? '');
      const startSeconds = Number.parseFloat(node.getAttribute('start') ?? '0');
      const durationSeconds = Number.parseFloat(node.getAttribute('dur') ?? '0');
      return {
        id: `cue-${index}`,
        text,
        startMs: Math.max(0, Math.round(startSeconds * 1000)),
        endMs: Math.max(0, Math.round((startSeconds + durationSeconds) * 1000)),
      };
    })
    .filter((cue) => cue.text.length > 0 && cue.endMs > cue.startMs);

  if (transcriptTextCues.length > 0) {
    return transcriptTextCues;
  }

  return parseSrv3TimedText(xmlDocument);
}

function parseSrv3TimedText(xmlDocument: Document): YoutubeSubtitleCue[] {
  const nodes = Array.from(xmlDocument.querySelectorAll('p'));
  return nodes
    .map((node, index) => {
      const text = normalizeCueText(node.textContent ?? '');
      const startMs = Math.max(0, Math.round(Number.parseFloat(node.getAttribute('t') ?? '0')));
      const explicitDurationMs = Number.parseFloat(node.getAttribute('d') ?? '');
      const nextStartMs = Number.parseFloat(nodes[index + 1]?.getAttribute('t') ?? '');
      const durationMs = Number.isFinite(explicitDurationMs)
        ? Math.max(0, Math.round(explicitDurationMs))
        : Number.isFinite(nextStartMs)
          ? Math.max(0, Math.round(nextStartMs - startMs))
          : 4000;

      return {
        id: `cue-${index}`,
        text,
        startMs,
        endMs: startMs + durationMs,
      };
    })
    .filter((cue) => cue.text.length > 0 && cue.endMs > cue.startMs);
}

function selectInitialTrackCues(cues: YoutubeSubtitleCue[]): YoutubeSubtitleCue[] {
  const video = document.querySelector('video');
  if (!video) {
    return cues.slice(0, FULL_TRACK_INITIAL_MAX_CUES);
  }

  const nowMs = Math.max(0, Math.round(video.currentTime * 1000));
  const nearestCue = cues.find(
    (cue) =>
      cue.endMs >= nowMs - FULL_TRACK_INITIAL_CUE_GRACE_MS &&
      cue.startMs <= nowMs + FULL_TRACK_INITIAL_CUE_GRACE_MS,
  );
  if (nearestCue) {
    return [nearestCue];
  }

  const lookaheadEndMs = nowMs + FULL_TRACK_INITIAL_LOOKAHEAD_MS;
  const visibleWindow = cues.filter(
    (cue) =>
      cue.endMs >= nowMs - FULL_TRACK_INITIAL_CUE_GRACE_MS &&
      cue.startMs <= lookaheadEndMs,
  );
  if (visibleWindow.length > 0) {
    return visibleWindow.slice(0, 1);
  }

  const firstWindowIndex = Math.max(
    0,
    cues.findIndex((cue) => cue.endMs >= nowMs - FULL_TRACK_INITIAL_CUE_GRACE_MS),
  );
  return cues.slice(firstWindowIndex, firstWindowIndex + 1);
}

async function collectRenderedYoutubeCaptionCues({
  enableAutoGeneratedCaptions,
}: {
  enableAutoGeneratedCaptions: boolean;
}): Promise<YoutubeSubtitleCue[]> {
  const immediateCue = collectImmediateRenderedYoutubeCaptionCue();
  if (immediateCue) {
    return [immediateCue];
  }

  if (enableAutoGeneratedCaptions) {
    await tryEnableYoutubeAutoGeneratedCaptions();
    const enabledText = collectRenderedYoutubeCaptionText();
    if (enabledText) {
      return [createRenderedYoutubeCaptionCue(enabledText)];
    }
  }

  const text = await waitForRenderedYoutubeCaptionText(RENDERED_CAPTION_WAIT_MS);
  if (!text) {
    return [];
  }

  return [createRenderedYoutubeCaptionCue(text)];
}

function collectImmediateRenderedYoutubeCaptionCue(): YoutubeSubtitleCue | null {
  const text = collectRenderedYoutubeCaptionText();
  if (!text) {
    return null;
  }

  return createRenderedYoutubeCaptionCue(text);
}

async function tryEnableYoutubeAutoGeneratedCaptions(): Promise<void> {
  const button = findYoutubeCaptionToggleButton();
  if (!button) {
    return;
  }

  const pressed = button.getAttribute('aria-pressed');
  const enabled =
    pressed === 'true' ||
    button.classList.contains('ytp-button-active') ||
    button.getAttribute('title')?.toLowerCase().includes('off');
  if (enabled) {
    return;
  }

  button.click();
  await sleep(350);
}

function findYoutubeCaptionToggleButton(): HTMLButtonElement | null {
  return (
    document.querySelector<HTMLButtonElement>('button.ytp-subtitles-button') ??
    document.querySelector<HTMLButtonElement>('.ytp-subtitles-button[role="button"]') ??
    document.querySelector<HTMLButtonElement>('[aria-label*="Subtitles"]') ??
    document.querySelector<HTMLButtonElement>('[aria-label*="字幕"]')
  );
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => {
    window.setTimeout(resolve, ms);
  });
}

function createRenderedYoutubeCaptionCue(text: string): YoutubeSubtitleCue {
  const video = document.querySelector('video');
  const nowMs = Math.max(0, Math.round((video?.currentTime ?? 0) * 1000));
  return {
    id: 'rendered-cue-0',
    text,
    startMs: Math.max(0, nowMs - 1000),
    endMs: nowMs + 60000,
  };
}

function waitForRenderedYoutubeCaptionText(timeoutMs: number): Promise<string> {
  return new Promise((resolve) => {
    let finished = false;
    let intervalId: number | undefined;
    let timeoutId: number | undefined;
    const host =
      document.querySelector('#movie_player') ??
      document.querySelector('.html5-video-player') ??
      document.body;
    const observer = new MutationObserver(() => {
      check();
    });

    function finish(text: string) {
      if (finished) {
        return;
      }
      finished = true;
      observer.disconnect();
      if (intervalId !== undefined) {
        window.clearInterval(intervalId);
      }
      if (timeoutId !== undefined) {
        window.clearTimeout(timeoutId);
      }
      resolve(text);
    }

    function check() {
      const text = collectRenderedYoutubeCaptionText();
      if (text) {
        finish(text);
      }
    }

    observer.observe(host, {
      childList: true,
      subtree: true,
      characterData: true,
    });
    intervalId = window.setInterval(check, 250);
    timeoutId = window.setTimeout(() => {
      logDebug('youtube rendered caption fallback wait timed out', {
        diagnostics: collectRenderedCaptionDiagnostics(),
      });
      finish('');
    }, timeoutMs);
    check();
  });
}

function collectRenderedYoutubeCaptionText(): string {
  const segmentText = collectCaptionTextFromSelector('.ytp-caption-segment');
  if (segmentText) {
    return segmentText;
  }

  return collectCaptionTextFromSelector(
    [
      '.caption-window .ytp-caption-segment',
      '.caption-window .caption-visual-line',
      '.caption-window .captions-text',
      '.caption-window span',
      '.ytp-caption-window-container .caption-visual-line',
      '.ytp-caption-window-container .captions-text',
      '.ytp-caption-window-container .caption-window',
      '.ytp-caption-window-container',
    ].join(','),
  );
}

function collectCaptionTextFromSelector(selector: string): string {
  const lines = Array.from(document.querySelectorAll<HTMLElement>(selector))
    .filter(isUsableCaptionElement)
    .map((node) => normalizeRenderedCaptionText(node.textContent ?? ''))
    .filter(Boolean);

  return uniqueStrings(lines).join(' ').trim();
}

function isUsableCaptionElement(element: HTMLElement): boolean {
  if (element.closest('[data-youtube-subtitle-overlay]')) {
    return false;
  }

  if (element.hidden || element.getAttribute('aria-hidden') === 'true') {
    return false;
  }

  const style = window.getComputedStyle(element);
  return style.display !== 'none' && style.visibility !== 'hidden' && style.opacity !== '0';
}

function normalizeRenderedCaptionText(text: string): string {
  return normalizeCueText(
    text
      .replace(/\u00a0/g, ' ')
      .replace(/\s*\n\s*/g, ' ')
      .replace(/\s+/g, ' '),
  );
}

function collectRenderedCaptionDiagnostics(): {
  selectorCounts: Array<{ selector: string; count: number; textPreview: string }>;
  playerTextPreview: string;
} {
  const selectors = [
    '.ytp-caption-segment',
    '.ytp-caption-window-container',
    '.caption-window',
    '.captions-text',
    '.caption-visual-line',
    '[class*="caption"]',
    '[aria-live]',
  ];
  return {
    selectorCounts: selectors.map((selector) => {
      const elements = Array.from(document.querySelectorAll<HTMLElement>(selector));
      return {
        selector,
        count: elements.length,
        textPreview: normalizeRenderedCaptionText(
          elements
            .slice(0, 3)
            .map((element) => element.textContent ?? '')
            .join(' '),
        ).slice(0, 160),
      };
    }),
    playerTextPreview: normalizeRenderedCaptionText(
      (
        document.querySelector('#movie_player') ??
        document.querySelector('.html5-video-player') ??
        document.body
      ).textContent ?? '',
    ).slice(0, 240),
  };
}

function normalizeCueText(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

function parseJson3TimedText(json: string): YoutubeSubtitleCue[] {
  try {
    const parsed = JSON.parse(json) as {
      events?: Array<{
        tStartMs?: number;
        dDurationMs?: number;
        segs?: Array<{ utf8?: string }>;
      }>;
    };

    return (parsed.events ?? [])
      .map((event, index) => {
        const text = normalizeCueText(
          (event.segs ?? []).map((segment) => segment.utf8 ?? '').join(''),
        );
        const startMs = Math.max(0, Math.round(event.tStartMs ?? 0));
        const durationMs = Math.max(0, Math.round(event.dDurationMs ?? 0));
        return {
          id: `cue-${index}`,
          text,
          startMs,
          endMs: startMs + durationMs,
        };
      })
      .filter((cue) => cue.text.length > 0 && cue.endMs > cue.startMs);
  } catch {
    return [];
  }
}

function parseWebVttTimedText(vtt: string): YoutubeSubtitleCue[] {
  return vtt
    .split(/\n\n+/)
    .map((block, index) => {
      const lines = block.split('\n').map((line) => line.trim()).filter(Boolean);
      const timingLineIndex = lines.findIndex((line) => line.includes('-->'));
      if (timingLineIndex === -1) {
        return null;
      }

      const [start, end] = lines[timingLineIndex].split('-->').map((value) => value.trim());
      const text = normalizeCueText(lines.slice(timingLineIndex + 1).join(' '));
      const startMs = parseVttTimestamp(start);
      const endMs = parseVttTimestamp(end);
      if (!text || endMs <= startMs) {
        return null;
      }

      return {
        id: `cue-${index}`,
        text,
        startMs,
        endMs,
      };
    })
    .filter((cue): cue is YoutubeSubtitleCue => cue !== null);
}

function parseVttTimestamp(timestamp: string): number {
  const normalized = timestamp.split(/\s+/)[0];
  const parts = normalized.split(':');
  const secondsText = parts.pop() ?? '0';
  const minutesText = parts.pop() ?? '0';
  const hoursText = parts.pop() ?? '0';
  const seconds = Number.parseFloat(secondsText);
  const minutes = Number.parseInt(minutesText, 10);
  const hours = Number.parseInt(hoursText, 10);

  return Math.round(((hours * 60 + minutes) * 60 + seconds) * 1000);
}
